import {chromium} from "playwright";import {mkdirSync,copyFileSync,appendFileSync,readFileSync,writeFileSync,existsSync} from "node:fs";import {resolve,dirname} from "node:path";import {fileURLToPath} from "node:url";
export const root=resolve(dirname(fileURLToPath(import.meta.url)),"../..");
export const statePath=resolve(root,".copilot-profile/workshop-capture-state.json");
export const state=existsSync(statePath)?JSON.parse(readFileSync(statePath,"utf8")):{};
export function remember(key,value){state[key]=value;writeFileSync(statePath,JSON.stringify(state,null,2));}
export function note(chapter,step,readme,ui){const line=`- ${chapter}, ${step}: README says ${readme}; UI shows ${ui}.`;const file=resolve(root,"_design/shots/NOTES.md");if(!readFileSync(file,"utf8").includes(line))appendFileSync(file,`\n${line}\n`);console.log("NOTE",step);}
export async function attach(){const browser=await chromium.connectOverCDP("http://127.0.0.1:9223");const context=browser.contexts()[0];context.setDefaultTimeout(15000);const page=context.pages().find(p=>p.url().includes("m365.cloud.microsoft/chat"))||await context.newPage();page.on('dialog',d=>d.accept());const session=await context.newCDPSession(page);await session.send('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});await session.detach();await page.setViewportSize({width:1600,height:900});if(!page.url().includes("m365.cloud.microsoft/chat"))await page.goto("https://m365.cloud.microsoft/chat",{waitUntil:"domcontentloaded",timeout:60000});await page.waitForTimeout(2000);if(page.url().includes("login.microsoftonline.com")&&await page.getByText((process.env.CAPTURE_ACCOUNT||"(no CAPTURE_ACCOUNT set)"),{exact:true}).count())await page.getByText((process.env.CAPTURE_ACCOUNT||"(no CAPTURE_ACCOUNT set)"),{exact:true}).click();if(!await page.getByRole("textbox",{name:"Canvas",exact:true,includeHidden:true}).count())await page.getByText(/^M365 Copilot \((?:Basic|Premium)\)\s*$/).first().waitFor({timeout:60000});if((await page.locator("body").innerText()).includes("M365 Copilot (Premium)"))throw Error("STOP_WHOLE_RUN: M365 Copilot (Premium)");return {browser,context,page};}
export async function stable(page){let last="";for(let i=0;i<12;i++){const text=await page.locator("body").innerText();if(text===last){await page.waitForTimeout(600);return;}last=text;await page.waitForTimeout(600);}}
export async function capture(page,chapter,name,{hover=false,mask=[]}={}){if(page.viewportSize()?.width!==1600||page.viewportSize()?.height!==900)await page.setViewportSize({width:1600,height:900});if(!hover)await page.mouse.move(1550,880);await stable(page);await page.waitForTimeout(800);const masks=page.frames().flatMap(f=>[f.getByRole("button",{name:/Work account|Account manager|Your profile/i,includeHidden:true}),f.locator('#mectrl_main_trigger,[data-tid="me-control-mini-avatar"],.fx-Avatar,.fui-Avatar'),f.getByText(process.env.CAPTURE_ACCOUNT||'(no account)',{exact:false}),f.locator('.fai-CopilotNavSubItem').filter({hasNotText:/^Laptop purchase - (comparison|quotation checklist)/})]);mkdirSync(resolve(root,chapter,"images"),{recursive:true});mkdirSync(resolve(root,"_design/shots/raw"),{recursive:true});const path=resolve(root,chapter,"images",name);await page.screenshot({path,mask:[...masks,...mask],maskColor:"#ffffff"});copyFileSync(path,resolve(root,"_design/shots/raw",name));console.log("SAVED",name);}
export async function send(page,prompt){prompt=prompt.replaceAll("[today's date]","14 October 2026");const stop=page.getByRole('button',{name:/^Stop/i}).first();await stop.waitFor({state:'hidden',timeout:180000});const box=page.getByRole('textbox',{name:/^Message (Copilot|Prompt Coach|Writing Coach|Quotation Checker)$/});await box.fill("");await box.focus();await page.keyboard.insertText(prompt);await page.waitForTimeout(1000);await page.getByRole('button',{name:'Send',exact:true}).click();await stop.waitFor({state:'visible',timeout:15000}).catch(()=>{});await stop.waitFor({state:'hidden',timeout:180000});await page.waitForTimeout(2500);await page.waitForFunction(p=>{const us=[...document.querySelectorAll('.fai-UserMessage')],u=us[us.length-1];const es=document.querySelectorAll('.fai-CopilotMessage'),e=es[es.length-1];return u&&u.innerText.replaceAll("\r", "").includes(p.replaceAll("\r", ""))&&e&&e.querySelector('[data-testid="CopyButtonTestId"]');},prompt,{timeout:180000});await stable(page);console.log('PROMPT_DONE',prompt.slice(0,65));}
export async function newChat(page,key){if(state[key]){await page.goto(state[key],{waitUntil:"domcontentloaded"});await page.getByRole("textbox",{name:"Message Copilot",exact:true}).waitFor({timeout:60000});await page.waitForTimeout(2500);return false;}await page.getByText("New chat",{exact:true}).first().click();await stable(page);return true;}
export async function lastAnswer(page){await page.getByRole("button",{name:"Copy Response",exact:true}).last().scrollIntoViewIfNeeded();await page.waitForTimeout(500);}
export async function debug(page){await page.screenshot({path:resolve(root,"_design/shots/debug-run.png"),mask:[page.getByRole("button",{name:/Work account/i,includeHidden:true})],maskColor:"#ffffff"});console.log("TAIL",(await page.locator("body").innerText()).slice(-2200));}


